import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Script from 'next/script'
import { GJCNavbar } from "@/components/gjc/gjcNavbar";
import GJCLeftSideBar from "@/components/gjc/gjcLeftSideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://cdn.tailwindcss.com"></Script>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <div className="relative min-h-screen">
            <GJCNavbar />
            <div className="flex pt-16"> {/* Add padding-top to account for navbar height */}
              <GJCLeftSideBar />
              <main className="flex-1 pl-64 container mx-auto pt-10"> {/* Add padding-left to account for sidebar width */}
                {children}
              </main>
            </div>
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}